### ISSUE TITLE
Flagged as trojan. I assume false positive?

### ISSUE THREAD

**Issue by dazza-bo** [FluffierKittens/SnowRunner-UI-Changes#1]
Hi, Windows Security blocked the SRUICInjector.exe file when I tried to download the .zip so I ran it through VirusTotal and it came back with this. I assume they're false positives but that seems like a lot of false positives? I thought I'd let you know either way.

![Screenshot 2023-07-20 134641](https://github.com/FluffierKittens/SnowRunner-UI-Changes/assets/5214844/44230e8c-8f93-4255-acaa-65ce541a2a96)

**Comment by FluffierKittens** [comment]
Yes, these are false positives. 

The nature of this mod is that it injects custom code (in a DLL) into an already-running process, in this case SnowRunner.exe. This allows it to modify or remove existing functionality of the game and add its own. 

Injecting DLLs into other processes like this is a technique that can be used by trojans or other malware to run malicious code in a way that allows it access to sensitive information, and without the user noticing. For that reason, this behavior gets flagged by anti-virus software using heuristic detection. 

Looking at that report, I see that it's flagged with a lot of non-specific terms like "generic," "unsafe," and "malicious." All they know is that SRUICInjector.exe is injecting a seemingly-random DLL into another running process, and that's enough to flag it. 

If this explanation isn't enough to make you confident in the compiled binaries I've provided, please feel free to compile the available source code yourself. This is in fact one of the main reasons I'm releasing the source code for this mod.
