### ISSUE TITLE
Not working TM (-edit updated game version)

### ISSUE THREAD

**Issue by DopedupPusher** [FluffierKittens/SnowRunner-UI-Changes#4]
Hey does 0.1.6 work on the latest snowrunner version? 
Before the game updated it worked perfectly but after the update it doesn't work anymore. 
I figured the game changed the SRUIC.dll file after update somehow so i extracted a fresh copy 
from the zip folder and added it to my SR root folder but no luck.

First line: SnowRunner UI Changes v0.1.6 (for version 1.468105.SNOW_DLC_12)
Second line: Initialized

**Comment by DopedupPusher** [comment]
PS checked my game version and it is 1.469305. Any chance of getting an updated version anytime soon?

**Comment by FluffierKittens** [comment]
Version 0.1.7 released; supports SnowRunner.exe version 1.469305.SNOW_DLC_12.
