### ISSUE TITLE
New game version

### ISSUE THREAD

**Issue by zjamnik** [FluffierKittens/SnowRunner-UI-Changes#5]
Snowrunner updated to Season 13 and it's crashing if this is running.

If possible I would also appreciate a version with only winch changes with auto reverse still available

**Comment by FluffierKittens** [comment]
Version 0.1.8 is released and is compatible with 1.510203.SNOW_DLC_13

Unfortunately I'm not able to maintain multiple versions with different feature sets. The source code is available, though, and I'd be happy to answer questions if you'd like to modify it to meet your needs.
